### PR TITLE
 Option to reset the current session  #283

### PR DESCRIPTION
**Pull request by AminTi**

### CODE REVIEW

**Comment by madkoo** [comment]
@AminTi  is this ready for review ? I see you are still pushing changes

**Comment by AminTi** [comment]
yes, it was ready, I've addressed your feedback. @madkoo

**Review by madkoo — APPROVED** [review]
Looks fine now 👍  :)

**Comment by HassanFad** [comment]
Hi [AminTi],
Today again  face the same issue that sessions are deleted again automatically after the session extension update on October 19th, 2023 to version 2,3.88. (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.estimate&ssr=false#overview)
Can you please take that into account and see what happens there? Or at last make it query based as suggested last time?  
Thanks. 
Hassan Fadili
DevOps MVP

**Comment by AminTi** [comment]
Hello Hassan, it seems that someone is deleting the sessions. Let's schedule a web session if you have the time. You can reach me at [amin.titi@solidify.dev](mailto:amin.titi@solidify.dev).

**Pull request merged**
